//SAGAS
export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';

//REDUCER
export const MOVIE_LIST_FETCHING = 'MOVIE_LIST_FETCHING';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAILURE = 'MOVIE_LIST_FAILURE';

export const MOVIE_SET_ACTIVE = 'MOVIE_SET_ACTIVE';